[toolchain]
anchor_version = "0.30.0"

[features]
skip-lint = false
seeds = true

[programs.devnet]
sol_xen = "9c17DFJhKFJx1jk6rqyobHUSXZCTmEoc9N44HQu14Hh8"


[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
# cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
