[toolchain]
anchor_version = "0.30.0"

[features]
skip-lint = false
seeds = true

[programs.devnet]
sol_xen = "Dx7zjkWZbUStmhjo8BrhbprtQCcMByJgCTEC6TLgkH8n"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
